"""
PULSE Slack Delivery
Sends morning brief via Slack Webhook.
"""

import httpx
from datetime import datetime, timezone
from typing import Dict, Any

from app.core.config import get_settings
from app.core.logging import get_logger

logger = get_logger("slack_delivery")
settings = get_settings()


async def send_slack_brief(brief: Dict[str, Any], execution_id: str) -> Dict[str, Any]:
    """
    Send morning brief via Slack webhook.
    
    Returns delivery status dict.
    """
    try:
        if not settings.SLACK_WEBHOOK_URL:
            logger.warning("Slack webhook not configured, skipping")
            return {
                "channel": "slack",
                "status": "skipped",
                "reason": "Slack webhook not configured",
            }

        blocks = _format_slack_blocks(brief)

        async with httpx.AsyncClient() as client:
            resp = await client.post(
                settings.SLACK_WEBHOOK_URL,
                json={"blocks": blocks},
            )

        if resp.status_code == 200:
            logger.info("Slack message sent successfully")
            return {
                "channel": "slack",
                "status": "delivered",
                "delivered_at": datetime.now(timezone.utc).isoformat(),
            }
        else:
            error = resp.text
            logger.error(f"Slack webhook error: {error}")
            return {
                "channel": "slack",
                "status": "failed",
                "error_message": error,
            }

    except Exception as e:
        logger.error(f"Slack delivery error: {e}")
        return {
            "channel": "slack",
            "status": "failed",
            "error_message": str(e),
        }


def _format_slack_blocks(brief: Dict[str, Any]) -> list:
    """Format brief as Slack Block Kit message."""
    priority = brief.get("priority_score", 5)
    emoji = ":red_circle:" if priority >= 8 else ":large_yellow_circle:" if priority >= 5 else ":large_green_circle:"

    blocks = [
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": "⚡ PULSE Morning Brief",
                "emoji": True,
            },
        },
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*{brief.get('greeting', 'Good morning!')}*",
            },
        },
        {
            "type": "section",
            "fields": [
                {
                    "type": "mrkdwn",
                    "text": f"{emoji} *Priority Score:* {priority}/10",
                },
                {
                    "type": "mrkdwn",
                    "text": f":dart: *Focus:* {brief.get('suggested_focus', '')}",
                },
                {
                    "type": "mrkdwn",
                    "text": f":calendar: *Meetings:* {brief.get('meetings', {}).get('count', 0)}",
                },
                {
                    "type": "mrkdwn",
                    "text": f":email: *Unread:* {brief.get('emails', {}).get('unread_important', 0)}",
                },
            ],
        },
        {"type": "divider"},
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*Executive Summary*\n{brief.get('executive_summary', '')}",
            },
        },
    ]

    # Add urgent items
    urgent = brief.get("urgent_items", [])
    if urgent:
        urgent_text = "\n".join(
            f"• *{item.get('item', '')}* ({item.get('source', '')})"
            for item in urgent[:5]
        )
        blocks.append({
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f":rotating_light: *Urgent Items*\n{urgent_text}",
            },
        })

    # Weather
    weather = brief.get("weather", {})
    blocks.append({
        "type": "section",
        "text": {
            "type": "mrkdwn",
            "text": f":partly_sunny: *Weather:* {weather.get('summary', 'N/A')}",
        },
    })

    # Tips
    tips = brief.get("productivity_tips", [])
    if tips:
        tips_text = "\n".join(f"• {tip}" for tip in tips[:3])
        blocks.append({
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f":bulb: *Tips*\n{tips_text}",
            },
        })

    # Footer
    blocks.append({
        "type": "context",
        "elements": [
            {
                "type": "mrkdwn",
                "text": f"_Generated by PULSE • Powered by Amazon Bedrock_ • {datetime.now(timezone.utc).strftime('%H:%M UTC')}",
            }
        ],
    })

    return blocks
